---
- set_fact:
    service_name: 'httpd'
  when: ansible_distribution_major_version == '7'

- set_fact:
    service_name: 'httpd24-httpd'
  when: ansible_distribution_major_version == '6'

- name: Install Apache (Centos7)
  block:
    - package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mod_ssl
  when: ansible_distribution_major_version == '7'

- name: Install Apache (Centos6)
  block:
    - package:
        name: httpd
        state: absent
    - package:
        name: "{{ item }}"
        state: latest
      with_items:
        - centos-release-scl
        - httpd24
        - httpd24-mod_ssl
    - file:
        src: /opt/rh/httpd24/root/etc/httpd
        dest: /etc/httpd
        state: link
    - file:
        src: /opt/rh/httpd24/root/usr/libexec/httpd-ssl-pass-dialog
        dest: /usr/libexec/httpd-ssl-pass-dialog
        state: link
  when: ansible_distribution_major_version == '6'

- name: Ensure default document root
  file:
    path: /var/www/html
    state: directory

- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: yes

- name: Create directory to store certificates
  tags: certificates
  file:
    path: "{{ ssl_cert_directory }}"
    state: directory

- name: Copy CA certificate public key
  tags: certificates
  copy:
    src: "{{ apache_certificates.ca_cert_src }}"
    dest: "{{ apache_certificates.ca_cert_dest }}"
  notify: restart apache

- name: Copy server certificate private key
  tags: certificates
  copy:
    src: "{{ apache_certificates.server_key_src }}"
    dest: "{{ apache_certificates.server_key_dest }}"
  notify: restart apache

- name: Copy server certificate public key
  tags: certificates
  copy:
    src: "{{ apache_certificates.server_cert_src }}"
    dest: "{{ apache_certificates.server_cert_dest }}"
  notify: restart apache

- name: Create apache log directory
  file:
    path: "{{ apache_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart apache

- name: Apply httpd.conf
  template:
    src: httpd24.conf.j2
    dest: "{{ apache_path }}/conf/httpd.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Apply ssl.conf
  template:
    src: ssl.conf.j2
    dest: "{{ apache_path }}/conf.d/ssl.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Apply vhosts
  template:
    src: vhost.conf.j2
    dest: "{{ apache_path }}/conf.d/{{ apache_vhosts_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
